window.EQUIPOS = [
  {
    "id": "grua-telescopica",
    "pagina": "renta-gruas-telescopicas.html",
    "nombre": "Renta de Grúas Telescópicas",
    "categoria": "gruas",
    "etiqueta": "Izaje y gran alcance",
    "capacidad": "La capacidad se define con peso, radio, longitud de pluma y configuración de la maniobra.",
    "uso": "Montaje de maquinaria, estructuras, obra civil, izajes industriales y maniobras especiales.",
    "descripcion": "Grúas móviles telescópicas para montajes, estructuras, maquinaria, obra civil e izajes industriales. Seleccionamos la unidad según peso, altura, radio de trabajo, accesos y condiciones del terreno.",
    "imagen": "assets/catalogo/grua-telescopica-xcmg-5ejes.webp",
    "imagenAlt": "Renta de Grúa Telescópica para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/gruas-telescopicas-grove.webp",
      "assets/catalogo/gruas-telescopicas-xcmg.webp",
      "assets/catalogo/maniobra-doble-grua-tanque.webp"
    ],
    "featured": true,
    "aliases": [
      "Renta Grúa Telescópica",
      "Renta de Grúas Telescópicas 01",
      "Renta de Grúas Telescópicas 02",
      "Renta de Grúas Telescópicas 03"
    ],
    "catalogVisible": true,
    "variantes": [
      "Grúa Telescópica 01",
      "Grúa Telescópica 02",
      "Grúa Telescópica 03"
    ]
  },
  {
    "id": "grua-telescopica-01",
    "pagina": "renta-gruas-telescopicas.html",
    "nombre": "Renta de Grúas Telescópicas 01",
    "categoria": "gruas",
    "etiqueta": "Unidad telescópica 01",
    "capacidad": "Tonelaje, pluma, radio y configuración sujetos a la unidad disponible y a la maniobra.",
    "uso": "Izajes, montajes, estructuras y movimiento de maquinaria.",
    "descripcion": "Unidad telescópica identificada como variante 01 dentro del catálogo.",
    "imagen": "assets/catalogo/grua-telescopica-xcmg-5ejes.webp",
    "imagenAlt": "Renta de Grúas Telescópicas 01 para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/maniobra-doble-grua-tanque.webp"
    ],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-telescopica-02",
    "pagina": "renta-gruas-telescopicas.html",
    "nombre": "Renta de Grúas Telescópicas 02",
    "categoria": "gruas",
    "etiqueta": "Unidad telescópica 02",
    "capacidad": "Tonelaje, pluma, radio y configuración sujetos a la unidad disponible y a la maniobra.",
    "uso": "Izajes industriales, montaje y obra civil.",
    "descripcion": "Variante 02 de grúa telescópica para maniobras donde se necesita alcance y control de carga.",
    "imagen": "assets/catalogo/gruas-telescopicas-grove.webp",
    "imagenAlt": "Renta de Grúas Telescópicas 02 para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/grua-rough-terrain-grove-rt600e.webp"
    ],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-telescopica-03",
    "pagina": "renta-gruas-telescopicas.html",
    "nombre": "Renta de Grúas Telescópicas 03",
    "categoria": "gruas",
    "etiqueta": "Unidad telescópica 03",
    "capacidad": "Tonelaje, pluma, radio y configuración sujetos a la unidad disponible y a la maniobra.",
    "uso": "Montajes, estructuras, maquinaria y trabajos de gran alcance.",
    "descripcion": "Variante 03 del catálogo de grúas telescópicas. La selección final se valida técnicamente antes de confirmar el servicio.",
    "imagen": "assets/catalogo/gruas-telescopicas-xcmg.webp",
    "imagenAlt": "Renta de Grúas Telescópicas 03 para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/grua-telescopica-xcmg-5ejes.webp"
    ],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-sany-stc350s",
    "pagina": "renta-gruas-telescopicas.html",
    "nombre": "Grúa móvil SANY STC350S",
    "categoria": "gruas",
    "etiqueta": "Grúa móvil sobre camión",
    "capacidad": "Capacidad, radio y configuración se confirman con la carta de carga y condiciones del proyecto.",
    "uso": "Izaje, construcción, montaje de equipos y maniobras industriales.",
    "descripcion": "Equipo móvil para izaje, montaje y apoyo en proyectos industriales y de construcción. La configuración final se revisa de acuerdo con la maniobra solicitada.",
    "imagen": "assets/catalogo/grua-sany-stc350s.webp",
    "imagenAlt": "Grúa móvil SANY STC350S para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": true
  },
  {
    "id": "grua-todo-terreno",
    "pagina": "renta-gruas-todo-terreno.html",
    "nombre": "Renta de Grúas Todo Terreno",
    "categoria": "gruas",
    "etiqueta": "Rough Terrain",
    "capacidad": "La capacidad y el alcance se determinan según modelo, radio de trabajo y condiciones del terreno.",
    "uso": "Patios industriales, obra, maniobras en terreno irregular y montajes.",
    "descripcion": "Grúas compactas y maniobrables para patios, obra y terrenos irregulares donde se requiere movilidad dentro del sitio de trabajo.",
    "imagen": "assets/catalogo/grua-rough-terrain-grove-rt600e.webp",
    "imagenAlt": "Renta de Grúa Todo Terreno / Rough Terrain para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/grua-rough-terrain-grove-rt500e.webp",
      "assets/catalogo/grua-movil-roja.webp"
    ],
    "featured": true,
    "aliases": [],
    "catalogVisible": true,
    "variantes": [
      "Grove RT600E",
      "Grove RT500E"
    ]
  },
  {
    "id": "grua-titan",
    "pagina": "renta-gruas-titan.html",
    "nombre": "Renta de Grúas Titán",
    "categoria": "gruas",
    "etiqueta": "Carga, traslado y maniobra",
    "capacidad": "Opciones comerciales de 10 y 30 toneladas; la capacidad efectiva depende del radio, estabilizadores y configuración.",
    "uso": "Carga y descarga, postes, maquinaria, materiales, equipos y apoyo en montajes.",
    "descripcion": "Camiones grúa tipo Titán para integrar carga, traslado, descarga y colocación dentro de una misma operación.",
    "imagen": "assets/catalogo/grua-titan-national-crane.webp",
    "imagenAlt": "Renta de Grúas Titán para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/grua-titan-negra.webp"
    ],
    "featured": true,
    "aliases": [
      "Renta Grúas Tipo Titán 01",
      "Renta de Grúas 10 Toneladas",
      "Renta de Grúas 30 Toneladas",
      "Renta de Grúas Tipo Titán 10 Toneladas",
      "Renta de Grúas Tipo Titán 30 Toneladas"
    ],
    "catalogVisible": true,
    "variantes": [
      "Titán 01",
      "Titán 10 toneladas",
      "Titán 30 toneladas 01",
      "Titán 30 toneladas 02",
      "Titán 30 toneladas 03",
      "Titán 30 toneladas 04"
    ]
  },
  {
    "id": "grua-titan-01",
    "pagina": "renta-gruas-titan.html",
    "nombre": "Renta Grúas Tipo Titán 01",
    "categoria": "gruas",
    "etiqueta": "Titán 01",
    "capacidad": "Capacidad y alcance sujetos a la unidad disponible; confirmar carta de carga.",
    "uso": "Carga, descarga, traslado y apoyo en montajes.",
    "descripcion": "Variante 01 de grúa tipo Titán.",
    "imagen": "assets/catalogo/grua-titan-negra.webp",
    "imagenAlt": "Renta Grúas Tipo Titán 01 para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-titan-10",
    "pagina": "renta-gruas-titan.html",
    "nombre": "Renta de Grúas Tipo Titán 10 Toneladas",
    "categoria": "gruas",
    "etiqueta": "Titán 10 t",
    "capacidad": "Categoría comercial de 10 toneladas. La capacidad efectiva cambia con radio, estabilizadores y configuración; confirmar carta de carga.",
    "uso": "Carga, descarga, traslado y colocación de equipos o materiales.",
    "descripcion": "Opción tipo Titán para trabajos de menor y mediana escala.",
    "imagen": "assets/catalogo/grua-titan-national-crane.webp",
    "imagenAlt": "Renta de Grúas Tipo Titán 10 Toneladas para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-10t",
    "pagina": "renta-gruas-titan.html",
    "nombre": "Renta de Grúas 10 Toneladas",
    "categoria": "gruas",
    "etiqueta": "Categoría 10 t",
    "capacidad": "Referencia comercial de 10 toneladas; capacidad efectiva depende de radio y configuración.",
    "uso": "Carga, descarga, maniobras y montaje.",
    "descripcion": "Categoría de grúa solicitada en el inventario comercial. El equipo final se confirma de acuerdo con la maniobra.",
    "imagen": "assets/catalogo/grua-titan-national-crane.webp",
    "imagenAlt": "Renta de Grúas 10 Toneladas para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-30t",
    "pagina": "renta-gruas-titan.html",
    "nombre": "Renta de Grúas 30 Toneladas",
    "categoria": "gruas",
    "etiqueta": "Categoría 30 t",
    "capacidad": "Referencia comercial de 30 toneladas; capacidad efectiva depende de radio y configuración.",
    "uso": "Izajes, montajes, carga y descarga de equipos pesados.",
    "descripcion": "Categoría de 30 toneladas dentro del portafolio. La unidad exacta se confirma al revisar peso, radio y condiciones del sitio.",
    "imagen": "assets/catalogo/grua-titan-negra.webp",
    "imagenAlt": "Renta de Grúas 30 Toneladas para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-titan-30-01",
    "pagina": "renta-gruas-titan.html",
    "nombre": "Renta de Grúas Tipo Titán 30 Toneladas 01",
    "categoria": "gruas",
    "etiqueta": "Titán 30 t · 01",
    "capacidad": "Categoría comercial 30 t; validar capacidad efectiva y carta de carga de la unidad.",
    "uso": "Montaje, carga, descarga y movimiento de equipos.",
    "descripcion": "Variante 01 dentro de la familia Titán 30 toneladas.",
    "imagen": "assets/catalogo/grua-titan-negra.webp",
    "imagenAlt": "Renta de Grúas Tipo Titán 30 Toneladas 01 para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-titan-30-02",
    "pagina": "renta-gruas-titan.html",
    "nombre": "Renta de Grúas Tipo Titán 30 Toneladas 02",
    "categoria": "gruas",
    "etiqueta": "Titán 30 t · 02",
    "capacidad": "Categoría comercial 30 t; validar capacidad efectiva y carta de carga de la unidad.",
    "uso": "Montaje, carga, descarga y movimiento de equipos.",
    "descripcion": "Variante 02 dentro de la familia Titán 30 toneladas.",
    "imagen": "assets/catalogo/grua-titan-national-crane.webp",
    "imagenAlt": "Renta de Grúas Tipo Titán 30 Toneladas 02 para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-titan-30-03",
    "pagina": "renta-gruas-titan.html",
    "nombre": "Renta de Grúas Tipo Titán 30 Toneladas 03",
    "categoria": "gruas",
    "etiqueta": "Titán 30 t · 03",
    "capacidad": "Categoría comercial 30 t; validar capacidad efectiva y carta de carga de la unidad.",
    "uso": "Montaje, carga, descarga y movimiento de equipos.",
    "descripcion": "Variante 03 dentro de la familia Titán 30 toneladas.",
    "imagen": "assets/catalogo/maniobra-izaje-industrial.webp",
    "imagenAlt": "Renta de Grúas Tipo Titán 30 Toneladas 03 para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-titan-30-04",
    "pagina": "renta-gruas-titan.html",
    "nombre": "Renta de Grúas Tipo Titán 30 Toneladas 04",
    "categoria": "gruas",
    "etiqueta": "Titán 30 t · 04",
    "capacidad": "Categoría comercial 30 t; validar capacidad efectiva y carta de carga de la unidad.",
    "uso": "Montaje, carga, descarga y movimiento de equipos.",
    "descripcion": "Variante 04 dentro de la familia Titán 30 toneladas.",
    "imagen": "assets/catalogo/grua-titan-negra.webp",
    "imagenAlt": "Renta de Grúas Tipo Titán 30 Toneladas 04 para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "grua-hiab",
    "pagina": "renta-gruas-hiab.html",
    "nombre": "Renta de Grúas HIAB",
    "categoria": "gruas",
    "etiqueta": "Brazo articulado sobre camión",
    "capacidad": "Capacidad y alcance según unidad disponible, radio de trabajo y condiciones de la maniobra.",
    "uso": "Carga, descarga, posicionamiento de materiales y trabajos con acceso controlado.",
    "descripcion": "Grúas articuladas montadas sobre camión para carga, descarga y colocación de materiales o equipos con alta versatilidad.",
    "imagen": "https://upload.wikimedia.org/wikipedia/commons/3/3d/HIAB_XS_700_HIPRO_truck_mounted_crane.jpg",
    "imagenAlt": "Renta de Grúas HIAB para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": true
  },
  {
    "id": "maniobras-industriales",
    "nombre": "Maniobras industriales y montajes",
    "categoria": "gruas",
    "etiqueta": "Servicio integral",
    "capacidad": "La combinación de equipos se define según peso, altura, accesos, terreno y alcance requerido.",
    "uso": "Montaje de maquinaria, estructuras, carga y descarga, movimiento industrial y maniobras especiales.",
    "descripcion": "Planeación y ejecución de maniobras para movimiento, montaje y posicionamiento de equipos, estructuras y cargas industriales.",
    "imagen": "assets/catalogo/maniobra-izaje-industrial.webp",
    "imagenAlt": "Maniobras industriales y montajes para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/maniobra-doble-grua-tanque.webp"
    ],
    "featured": true,
    "aliases": [],
    "catalogVisible": true,
    "pagina": "maniobras-industriales.html"
  },
  {
    "id": "plataforma-telescopica",
    "pagina": "renta-plataformas-aereas.html",
    "nombre": "Renta de Plataformas Aéreas Telescópicas",
    "categoria": "altura",
    "etiqueta": "Alcance directo en altura",
    "capacidad": "Altura de trabajo, alcance y capacidad de plataforma según modelo disponible.",
    "uso": "Mantenimiento, instalaciones, fachadas, estructuras y trabajos exteriores en altura.",
    "descripcion": "Plataformas de brazo telescópico para trabajos que requieren gran alcance horizontal y altura de trabajo.",
    "imagen": "assets/catalogo/plataforma-telescopica-jlg-660sj.webp",
    "imagenAlt": "Renta Plataforma Aérea Telescópica para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/plataforma-telescopica-genie-s125.webp",
      "assets/catalogo/plataforma-telescopica-genie.webp",
      "assets/catalogo/plataforma-telescopica-zoomlion.webp"
    ],
    "featured": true,
    "aliases": [
      "Renta Plataforma Aérea Telescópica",
      "Renta Genie Manlift Elevador"
    ],
    "catalogVisible": true,
    "variantes": [
      "JLG 660SJ",
      "Genie S-125",
      "Genie / Manlift",
      "Zoomlion telescópica"
    ]
  },
  {
    "id": "plataforma-aerea-articulada",
    "pagina": "renta-plataformas-aereas.html",
    "nombre": "Renta de Plataformas Aéreas Articuladas",
    "categoria": "altura",
    "etiqueta": "Acceso alrededor de obstáculos",
    "capacidad": "Altura de trabajo y alcance lateral según modelo disponible.",
    "uso": "Mantenimiento industrial, fachadas, instalaciones, pintura y montajes.",
    "descripcion": "Plataformas articuladas para mantenimiento, instalación y montaje donde se necesita trabajar alrededor de estructuras u obstáculos.",
    "imagen": "assets/catalogo/plataforma-articulada-jlg-600aj.webp",
    "imagenAlt": "Renta Plataforma Aérea Articulada para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/plataforma-articulada-azul.webp",
      "assets/catalogo/plataforma-articulada-genie.webp",
      "assets/catalogo/plataforma-articulada-extendida.webp"
    ],
    "featured": true,
    "aliases": [
      "Renta Plataforma Aérea Articulada",
      "Renta de Plataforma Articulada"
    ],
    "catalogVisible": true,
    "variantes": [
      "JLG 600AJ",
      "Plataforma articulada",
      "Genie articulada"
    ]
  },
  {
    "id": "plataforma-articulada",
    "pagina": "renta-plataformas-aereas.html",
    "nombre": "Renta de Plataforma Articulada",
    "categoria": "altura",
    "etiqueta": "Brazo articulado",
    "capacidad": "Altura y alcance lateral dependen del modelo disponible.",
    "uso": "Mantenimiento, instalaciones, pintura y trabajo en altura con obstáculos.",
    "descripcion": "Otra variante comercial de plataforma articulada dentro del inventario.",
    "imagen": "assets/catalogo/plataforma-articulada-azul.webp",
    "imagenAlt": "Renta de Plataforma Articulada para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/plataforma-articulada-genie.webp"
    ],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "genie-manlift",
    "pagina": "renta-plataformas-aereas.html",
    "nombre": "Renta Genie (Manlift / Elevador)",
    "categoria": "altura",
    "etiqueta": "Manlift",
    "capacidad": "Modelo y alcance sujetos a disponibilidad. En el banco real aparecen equipos Genie de brazo y elevación personal.",
    "uso": "Mantenimiento industrial, naves, fachadas e instalaciones.",
    "descripcion": "Equipo de elevación Genie / Manlift para acceso controlado de personal a zonas de trabajo en altura.",
    "imagen": "assets/catalogo/plataforma-telescopica-genie-s125.webp",
    "imagenAlt": "Renta Genie (Manlift / Elevador) para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/plataforma-articulada-genie.webp",
      "assets/catalogo/plataforma-personal-genie-awp25s.webp"
    ],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "plataforma-tijera",
    "pagina": "renta-plataformas-aereas.html",
    "nombre": "Renta de Plataformas Tipo Tijera",
    "categoria": "altura",
    "etiqueta": "Elevación vertical",
    "capacidad": "Altura de trabajo y capacidad según modelo disponible.",
    "uso": "Instalaciones, mantenimiento, almacenes, naves y trabajos verticales.",
    "descripcion": "Plataformas tipo tijera para elevar personal y herramientas de forma vertical sobre una base estable.",
    "imagen": "assets/catalogo/plataforma-tijera-genie-gs1930.webp",
    "imagenAlt": "Renta de Plataforma Aérea Tipo Tijera 01 para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/plataforma-tijera-genie-gs1930-02.webp",
      "assets/catalogo/plataforma-tijera-azul.webp"
    ],
    "featured": false,
    "aliases": [],
    "catalogVisible": true,
    "variantes": [
      "Genie GS-1930",
      "Tijera eléctrica / compacta"
    ]
  },
  {
    "id": "plataforma-personal",
    "pagina": "renta-plataformas-aereas.html",
    "nombre": "Renta de Plataforma Aérea Personal",
    "categoria": "altura",
    "etiqueta": "Acceso compacto",
    "capacidad": "Altura de trabajo y configuración según unidad disponible.",
    "uso": "Mantenimiento, electricidad, almacenes, instalaciones y trabajos interiores.",
    "descripcion": "Plataforma compacta para trabajos puntuales de mantenimiento e instalación donde se requiere elevación vertical de una persona.",
    "imagen": "assets/catalogo/plataforma-personal-genie-awp25s.webp",
    "imagenAlt": "Renta de Plataforma Aérea Tipo Personal 01 para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": true
  },
  {
    "id": "camion-canastilla",
    "pagina": "renta-camion-canastilla.html",
    "nombre": "Renta de Camión Canastilla",
    "categoria": "altura",
    "etiqueta": "Trabajo aéreo móvil",
    "capacidad": "Altura y alcance de trabajo según unidad disponible.",
    "uso": "Mantenimiento, alumbrado, instalaciones, poda técnica y servicios en altura.",
    "descripcion": "Camión con canastilla para trabajos en altura que requieren movilidad y acceso desde vía o superficie de trabajo.",
    "imagen": "assets/catalogo/camion-canastilla.webp",
    "imagenAlt": "Renta de Camión Canastilla para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": true
  },
  {
    "id": "telehandler",
    "pagina": "renta-manipuladores-telescopicos.html",
    "nombre": "Renta de Manipulador Telescópico / Telehandler",
    "categoria": "logistica",
    "etiqueta": "Elevación y manejo de materiales",
    "capacidad": "Capacidad y altura de elevación según modelo, implemento y condiciones de operación.",
    "uso": "Movimiento de materiales, carga, descarga y abastecimiento en altura.",
    "descripcion": "Manipulador telescópico para mover, elevar y posicionar materiales en obra, patios y entornos industriales.",
    "imagen": "assets/catalogo/telehandler-genie-gth1056.webp",
    "imagenAlt": "Renta de Manipulador Telescópico / Telehandler para renta y trabajos industriales",
    "galeria": [],
    "featured": true,
    "aliases": [],
    "catalogVisible": true
  },
  {
    "id": "manipulador-estabilizadores",
    "pagina": "renta-manipuladores-telescopicos.html",
    "nombre": "Equipo de manipulación con brazo y estabilizadores",
    "categoria": "logistica",
    "etiqueta": "Manipulación especializada",
    "capacidad": "Capacidad y alcance sujetos a la configuración del equipo y a la maniobra.",
    "uso": "Movimiento, posicionamiento y apoyo en maniobras industriales.",
    "descripcion": "Equipo especializado para elevación y manipulación de cargas con estabilizadores, diseñado para trabajos que requieren precisión y apoyo adicional.",
    "imagen": "assets/catalogo/equipo-manipulacion-brazo-01.webp",
    "imagenAlt": "Equipo especial de manipulación con brazo y estabilizadores para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/equipo-manipulacion-brazo-02.webp"
    ],
    "featured": false,
    "aliases": [],
    "catalogVisible": true
  },
  {
    "id": "montacargas-01",
    "pagina": "renta-montacargas.html",
    "nombre": "Renta de Montacargas",
    "categoria": "logistica",
    "etiqueta": "Movimiento de carga",
    "capacidad": "Capacidad de carga según la unidad seleccionada y las condiciones de operación.",
    "uso": "Carga y descarga, almacenes, patios, plantas y movimiento de equipos.",
    "descripcion": "Montacargas para carga, descarga y movimiento de materiales en industria, almacenes, patios y obra.",
    "imagen": "assets/catalogo/montacargas-hyster-50.webp",
    "imagenAlt": "Renta Montacargas 01 para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/montacargas-toyota.webp",
      "assets/catalogo/montacargas-hyster-155.webp"
    ],
    "featured": true,
    "aliases": [
      "Renta Montacargas 01",
      "Renta de Montacargas 02"
    ],
    "catalogVisible": true,
    "variantes": [
      "Montacargas 01",
      "Montacargas 02",
      "Hyster",
      "Toyota"
    ]
  },
  {
    "id": "montacargas-02",
    "pagina": "renta-montacargas.html",
    "nombre": "Renta de Montacargas 02",
    "categoria": "logistica",
    "etiqueta": "Montacargas 02",
    "capacidad": "Capacidad por confirmar según la unidad disponible y la carga.",
    "uso": "Movimiento de materiales, carga y descarga en patios, naves y almacenes.",
    "descripcion": "Montacargas variante 02 con",
    "imagen": "assets/catalogo/montacargas-toyota.webp",
    "imagenAlt": "Renta de Montacargas 02 para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "montacargas",
    "pagina": "renta-montacargas.html",
    "nombre": "Renta de Montacargas",
    "categoria": "logistica",
    "etiqueta": "Familia de montacargas",
    "capacidad": "Capacidad y tipo de combustible/equipo por confirmar según disponibilidad.",
    "uso": "Carga, descarga y movimiento de materiales.",
    "descripcion": "Registro general usado por el cotizador para la familia de montacargas.",
    "imagen": "assets/catalogo/montacargas-hyster-50.webp",
    "imagenAlt": "Renta de Montacargas para renta y trabajos industriales",
    "galeria": [
      "assets/catalogo/montacargas-toyota.webp",
      "assets/catalogo/montacargas-hyster-155.webp"
    ],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "retroexcavadora",
    "pagina": "renta-retroexcavadoras.html",
    "nombre": "Renta de Retroexcavadoras",
    "categoria": "maquinaria",
    "etiqueta": "Excavación y movimiento",
    "capacidad": "Modelo, cucharón y aditamentos según disponibilidad y condiciones del terreno.",
    "uso": "Zanjas, cimentaciones, nivelación, carga y movimiento de tierra.",
    "descripcion": "Retroexcavadoras para excavación, zanjas, preparación de terreno, carga y apoyo en obra civil.",
    "imagen": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/BackhoeLoader.jpg/1280px-BackhoeLoader.jpg",
    "imagenAlt": "Renta de Retroexcavadoras para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": true
  },
  {
    "id": "bobcat",
    "pagina": "renta-bobcat-minicargador.html",
    "nombre": "Renta de BOBCAT / Minicargador",
    "categoria": "maquinaria",
    "etiqueta": "Compacto y maniobrable",
    "capacidad": "Modelo, capacidad operativa y aditamentos según disponibilidad.",
    "uso": "Limpieza, carga, nivelación, patios y apoyo en obra.",
    "descripcion": "Minicargador para limpieza, carga, nivelación y movimiento de material en espacios reducidos.",
    "imagen": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Bobcat_S650_skid_steer_loader_%2815084521732%29.jpg/1280px-Bobcat_S650_skid_steer_loader_%2815084521732%29.jpg",
    "imagenAlt": "Renta BOBCAT Minicargador para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": true
  },
  {
    "id": "lowboy-01",
    "pagina": "renta-lowboy-cama-baja.html",
    "nombre": "Renta Lowboy Cama Baja 01",
    "categoria": "transporte",
    "etiqueta": "Cama baja 01",
    "capacidad": "Capacidad, ejes y dimensiones se confirman con el peso, dimensiones y ruta.",
    "uso": "Traslado de maquinaria, plataformas y equipos industriales.",
    "descripcion": "Variante 01 de cama baja / lowboy con",
    "imagen": "assets/catalogo/lowboy-plataforma-maquinaria.webp",
    "imagenAlt": "Renta Lowboy Cama Baja 01 para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "lowboy",
    "pagina": "renta-lowboy-cama-baja.html",
    "nombre": "Renta de Lowboy / Cama Baja",
    "categoria": "transporte",
    "etiqueta": "Transporte de maquinaria",
    "capacidad": "Configuración, ejes y capacidad según peso, dimensiones, origen, destino y ruta.",
    "uso": "Traslado de maquinaria pesada, plataformas y equipos industriales.",
    "descripcion": "Transporte especializado para maquinaria, plataformas y equipos que requieren una cama de menor altura.",
    "imagen": "assets/catalogo/lowboy-plataforma-maquinaria.webp",
    "imagenAlt": "Renta Lowboy / Cama Baja para renta y trabajos industriales",
    "galeria": [],
    "featured": true,
    "aliases": [
      "Renta Lowboy Cama Baja 01",
      "Renta de Plataforma Tráiler"
    ],
    "catalogVisible": true,
    "variantes": [
      "Lowboy / Cama Baja",
      "Lowboy Cama Baja 01",
      "Plataforma Tráiler"
    ]
  },
  {
    "id": "plataforma-trailer",
    "pagina": "renta-lowboy-cama-baja.html",
    "nombre": "Renta de Plataforma Tráiler",
    "categoria": "transporte",
    "etiqueta": "Plataforma de transporte",
    "capacidad": "Dimensiones, ejes y capacidad se revisan según el equipo o material a trasladar.",
    "uso": "Traslado de equipos, materiales, maquinaria y cargas especiales.",
    "descripcion": "Plataforma para transporte especializado. Se utiliza",
    "imagen": "assets/catalogo/lowboy-plataforma-maquinaria.webp",
    "imagenAlt": "Renta de Plataforma Tráiler para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": false
  },
  {
    "id": "plataforma-autos",
    "pagina": "renta-plataforma-autos.html",
    "nombre": "Renta de Plataforma para Autos",
    "categoria": "transporte",
    "etiqueta": "Traslado de vehículos",
    "capacidad": "Configuración para hasta 3 vehículos según unidad, dimensiones y disponibilidad.",
    "uso": "Movimiento y traslado de vehículos.",
    "descripcion": "Plataforma especializada para transporte de vehículos de acuerdo con la configuración disponible y la ruta del servicio.",
    "imagen": "https://upload.wikimedia.org/wikipedia/commons/9/99/Car_carrier_trailer_1.webp",
    "imagenAlt": "Renta de Plataformas para Autos, 3 Vehículos 01 para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": true
  },
  {
    "id": "torre-luz",
    "pagina": "renta-torres-de-luz.html",
    "nombre": "Renta de Torres de Luz",
    "categoria": "apoyo",
    "etiqueta": "Iluminación temporal",
    "capacidad": "Potencia, autonomía, altura de mástil y luminarias según equipo disponible.",
    "uso": "Obra nocturna, mantenimiento, patios y contingencias.",
    "descripcion": "Torres móviles para mantener frentes de trabajo, patios y operaciones nocturnas correctamente iluminados.",
    "imagen": "https://upload.wikimedia.org/wikipedia/commons/1/13/Light_tower_trailer_Shelby_Farms_Memphis_TN_2013-10-19_001.jpg",
    "imagenAlt": "Renta de Torres de Luz para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [
      "Renta Torre de Luz"
    ],
    "catalogVisible": true
  },
  {
    "id": "patin-pallet",
    "pagina": "renta-patin-pallet.html",
    "nombre": "Renta de Patín Pallet",
    "categoria": "logistica",
    "etiqueta": "Movimiento interno",
    "capacidad": "Capacidad de carga según unidad disponible.",
    "uso": "Movimiento de tarimas y cargas paletizadas.",
    "descripcion": "Equipo para recorridos cortos y manejo de carga paletizada en almacenes, patios y superficies adecuadas.",
    "imagen": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Pallet_Jack.jpg",
    "imagenAlt": "Renta de Patín Pallet para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": true
  },
  {
    "id": "andamios",
    "pagina": "renta-andamios.html",
    "nombre": "Renta de Andamios",
    "categoria": "apoyo",
    "etiqueta": "Acceso temporal",
    "capacidad": "Configuración, altura y cantidad de módulos según proyecto.",
    "uso": "Mantenimiento, fachadas, instalaciones y obra.",
    "descripcion": "Sistemas de acceso temporal para trabajos de mantenimiento, instalación y construcción.",
    "imagen": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Cincinnati-scaffolding.jpg/1280px-Cincinnati-scaffolding.jpg",
    "imagenAlt": "Renta de Andamios para renta y trabajos industriales",
    "galeria": [],
    "featured": false,
    "aliases": [],
    "catalogVisible": true
  }
];
